### ISSUE TITLE
Set KVM as default nova compute backend

### ISSUE THREAD

**Issue by cedriccastagnede** [clustervision/trinityX#214]
Hello,

In order to have instance starting properly, we must change in trinityX/configuration/images/nova-nodes.sh:
    openstack-config --set /etc/nova/nova.conf libvirt virt_type qemu
by:
    openstack-config --set /etc/nova/nova.conf libvirt virt_type kvm
    openstack-config --set /etc/nova/nova.conf libvirt cpu_mode host-model

Regards,

**Comment by hicham-a** [comment]
Thanks for reporting the issue.
Actually we check if the image is being built on a VM and set the virt_type to qemu (which is required when our compute nodes are VMs). Otherwise the defaults work just fine for baremetal nodes:

For some reason you got a false negative when checking for hardware virtualization support on this line
https://github.com/clustervision/trinityX/blob/development/configuration/images/nova-nodes.sh#L49

Maybe it would make more sense to get rid of this check and setting entirely.

**Comment by hicham-a** [comment]
When tested that snippet behaves as expected
On VMs without nested virtualization it results in virt_type = qemu:
```
# egrep -c '(vmx|svm)' /proc/cpuinfo
0
```
On baremetal it results in virt_type = kvm:
```
# egrep -c '(vmx|svm)' /proc/cpuinfo
8
```
Not sure why you got the issue.

**Comment by heatherLstephens** [comment]
not reproducible
