### ISSUE TITLE
Default packages on controller nodes

### ISSUE THREAD

**Issue by ig0rmeister** [clustervision/trinityX#290]
TrinityX:Development
Hello, 
I would suggest to add packages:
- dapl: required to provide libdat*.so* files for intel mkl benchmark
- libibverbs-utils: to have ibv_ tools by default
- group "Kernel Development": just because
- cv-zabbix-checks: for cv custom zabbix checks (also should be installed in default image)
- nmap, iperf3: good user reviews

**Comment by aphmschonewille** [comment]
Although the current state of OS packages is different than years ago, we strive for the current TrinityX Release to incorporate the most useful packages for mainstream usage. Some packages will be added, and others will not. E.g. Kernel development is not always preferred as not everyone will build or compile kernel (modules). Iperf3 and others on the other hand will be added if not done already. Others are deprecated  as the current TrinityX release has drastically changed since 2018.

If possible would you like to re-evaluate our current release for feedback?
