### ISSUE TITLE
Issue Logging in with OS-Based Users on TrinityX HPC (VirtualBox)

### ISSUE THREAD

**Issue by jjksaji** [clustervision/trinityX#437]
Good morning.

After successfully installing TrinityX HPC on VirtualBox (not in production, for exploration and learning), I managed to boot the nodes through PXE, create users via obdol, and log in using those obdol-created users. However, after some hours, I found that I could no longer log in with the original OS-based users, though I can still access the system using the obdol-created users.

When I checked /etc/passwd, there is no entry for the initial OS-based users. Is this behavior expected under TrinityX, or have I potentially misconfigured something?

Best regards,
Joseph John

**Comment by aphmschonewille** [comment]
Trinityx does not add users/groups directly into passwd/groups nor does it remove entries there. System or OS users are added during the installation of packages. Since we incorporate a DS (like openldap), regular users are managed there. I am not sure what happened, but what system users are missing, and are they missing in images or on the controller?
